apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/cannavit/knative-func-hello/hello:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
      imagePullSecrets:
        - name: container-registry


  